<template>
  <div v-if="product">
    <h1 class="text-h4 mb-4">
      {{ product.name }}
    </h1>
    <v-card class="mb-4">
      <v-card-title>Details</v-card-title>
      <v-card-text>
        <v-text-field v-model="product.name" label="Name" variant="outlined" class="mb-2" @blur="updateProduct" />
        <v-text-field v-model="product.slug" label="Slug" variant="outlined" class="mb-2" @blur="updateProduct" />
        <RichTextField v-model="product.description" label="Description" class="product-description-editor" @blur="updateProduct" />
        <v-text-field
          v-model="product.barcode"
          label="Barcode"
          variant="outlined"
          class="mb-2"
          hint="Randomly generated by default. Shuffle to regenerate."
          persistent-hint
          @blur="updateProduct"
        >
          <template #append-inner>
            <div class="d-flex align-center ga-1">
              <v-btn
                size="small"
                variant="text"
                icon="mdi-shuffle-variant"
                :loading="generatingBarcode"
                @click="shuffleBarcode"
              />
              <v-btn
                size="small"
                variant="text"
                icon="mdi-camera-outline"
                @click="openScanDialog"
              />
            </div>
          </template>
        </v-text-field>
        <v-select
          v-model="product.brand_id"
          :items="brands"
          item-title="name"
          item-value="id"
          label="Brand model (optional)"
          variant="outlined"
          clearable
          class="mb-2"
          @update:model-value="updateProduct"
        >
          <template #append>
            <v-btn size="x-small" variant="text" icon @click="showBrandDialog = true">
              <v-icon>mdi-plus</v-icon>
            </v-btn>
          </template>
        </v-select>
        <v-autocomplete
          v-model="product.category_ids"
          :items="categories"
          item-title="name"
          item-value="id"
          label="Categories (optional)"
          variant="outlined"
          chips
          multiple
          clearable
          class="mb-2"
          @update:model-value="updateProduct"
        >
          <template #append>
            <v-btn size="x-small" variant="text" icon @click="showCategoryDialog = true">
              <v-icon>mdi-plus</v-icon>
            </v-btn>
          </template>
        </v-autocomplete>
        <v-autocomplete
          v-model="product.tag_ids"
          :items="tags"
          item-title="name"
          item-value="id"
          label="Tags (optional)"
          variant="outlined"
          chips
          multiple
          clearable
          class="mb-2"
          @update:model-value="updateProduct"
        >
          <template #append>
            <v-btn size="x-small" variant="text" icon @click="showTagDialog = true">
              <v-icon>mdi-plus</v-icon>
            </v-btn>
          </template>
        </v-autocomplete>
        <v-checkbox v-model="product.is_active" label="Active" @change="updateProduct" />
        <v-checkbox
          v-model="product.track_stock"
          :label="product.has_variants ? 'Default track stock for variants' : 'Track stock for this product'"
          @change="updateProduct"
        />
        <template v-if="product.has_variants">
          <v-divider class="my-3" />
          <div class="text-subtitle-2 mb-2">
            Option sets
          </div>
          <div v-for="(opt, idx) in optionSetsLocal" :key="idx" class="mb-3 pa-3 border rounded">
            <div class="d-flex align-center ga-2 mb-2">
              <v-text-field v-model="opt.name" label="Option" variant="outlined" density="comfortable" hide-details style="max-width: 180px" />
              <v-select
                v-model="opt.type"
                :items="optionTypeItems"
                item-title="title"
                item-value="value"
                label="Type"
                variant="outlined"
                density="comfortable"
                hide-details
                style="max-width: 220px"
              />
              <v-spacer />
              <v-btn icon variant="text" size="small" @click="optionSetsLocal.splice(idx, 1)">
                <v-icon>mdi-delete</v-icon>
              </v-btn>
            </div>
            <v-text-field
              v-if="opt.type === 'text'"
              v-model="opt.valuesText"
              label="Text values (comma-separated)"
              variant="outlined"
              density="comfortable"
              hide-details
            />
            <div v-else>
              <div v-for="(entry, eIdx) in opt.entries" :key="eIdx" class="d-flex align-center ga-2 mb-2">
                <v-text-field v-model="entry.label" label="Label *" variant="outlined" density="comfortable" hide-details />
                <div
                  v-if="opt.type === 'image'"
                  class="d-flex flex-column flex-grow-1"
                >
                  <div class="d-flex align-center ga-2">
                    <v-btn
                      v-if="!entry.value"
                      variant="outlined"
                      height="48"
                      class="justify-start text-none"
                      prepend-icon="mdi-image-search-outline"
                      @click="openImagePicker(idx, eIdx)"
                    >
                      Choose Image
                    </v-btn>
                    <button
                      v-else
                      type="button"
                      class="image-preview-btn"
                      @click="openImagePicker(idx, eIdx)"
                    >
                      <v-img :src="optionImageUrl(entry.value)" width="84" height="48" cover />
                    </button>
                  </div>
                </div>
                <v-text-field
                  v-else
                  v-model="entry.value"
                  type="color"
                  label="Color value *"
                  variant="outlined"
                  density="comfortable"
                  hide-details
                  style="max-width: 120px"
                />
                <v-btn icon variant="text" size="small" @click="opt.entries.splice(eIdx, 1)">
                  <v-icon>mdi-close</v-icon>
                </v-btn>
              </div>
              <v-btn size="small" variant="outlined" @click="opt.entries.push({ label: '', value: opt.type === 'color' ? '#000000' : '' })">
                Add {{ opt.type === 'image' ? 'image' : 'color' }} value
              </v-btn>
            </div>
          </div>
          <div class="d-flex ga-2">
            <v-btn variant="outlined" size="small" class="mt-2" @click="addOptionSet('text')">
              Add text option
            </v-btn>
            <v-btn variant="outlined" size="small" class="mt-2" @click="addOptionSet('image')">
              Add image option
            </v-btn>
            <v-btn variant="outlined" size="small" class="mt-2" @click="addOptionSet('color')">
              Add color option
            </v-btn>
          </div>
          <v-btn v-if="optionSetsChanged" color="primary" size="small" class="mt-2 ml-2" @click="saveOptionSets">
            Save option sets
          </v-btn>
        </template>
      </v-card-text>
    </v-card>
    <v-card class="mb-4">
      <v-card-title>Images</v-card-title>
      <v-card-text>
        <div class="d-flex flex-wrap gap-2 mb-3">
          <div v-for="img in images" :key="img.id" class="d-flex flex-column align-center">
            <v-img :src="imageUrl(img.path)" width="80" height="80" cover class="rounded" />
            <v-btn icon size="x-small" variant="text" class="mt-1" @click="deleteImage(img.id)">
              <v-icon>mdi-delete</v-icon>
            </v-btn>
          </div>
          <div class="d-flex align-center justify-center rounded bg-grey-lighten-2" style="width: 80px; height: 80px">
            <v-btn icon variant="text" @click="showProductImagePicker = true">
              <v-icon>mdi-plus</v-icon>
            </v-btn>
          </div>
        </div>
        <p class="text-caption text-medium-emphasis">
          Add images from Storage Explorer. You can also upload JPEG, PNG or WebP there (max 5MB).
        </p>
      </v-card-text>
    </v-card>
    <v-card>
      <v-card-title class="d-flex align-center flex-wrap gap-2">
        Variants
        <v-btn color="primary" size="small" @click="showVariant = true">
          Add variant
        </v-btn>
        <template v-if="product.has_variants && product.option_sets?.length">
          <v-btn variant="outlined" size="small" :loading="generating" @click="generateVariants">
            Generate from options
          </v-btn>
        </template>
        <v-spacer />
        <template v-if="selectedIds.length > 0">
          <span class="text-body-2">{{ selectedIds.length }} selected</span>
          <v-text-field v-model="bulkPrice" type="number" min="0" step="0.01" placeholder="Set price" density="compact" hide-details style="max-width: 120px" />
          <v-text-field v-model="bulkStock" type="number" min="0" placeholder="Set stock" density="compact" hide-details style="max-width: 100px" />
          <v-btn size="small" :loading="bulkSaving" @click="applyBulkEdit">
            Apply
          </v-btn>
          <v-btn variant="text" size="small" @click="selectedIds = []">
            Clear
          </v-btn>
        </template>
      </v-card-title>
      <v-card-text>
        <v-table>
          <thead>
            <tr>
              <th v-if="variants.length > 1" style="width: 40px">
                <v-checkbox
                  :model-value="selectedIds.length === variants.length"
                  :indeterminate="selectedIds.length > 0 && selectedIds.length < variants.length"
                  hide-details
                  density="compact"
                  @click="toggleSelectAll"
                />
              </th>
              <th v-for="optName in optionColumns" :key="optName">
                {{ optName }}
              </th>
              <th>Name</th>
              <th>SKU</th>
              <th>Price</th>
              <th>Track stock</th>
              <th>Stock</th>
              <th v-if="variants.length > 1" />
            </tr>
          </thead>
          <tbody>
            <tr v-for="v in variants" :key="v.id">
              <td v-if="variants.length > 1">
                <v-checkbox
                  :model-value="selectedIds.includes(v.id)"
                  hide-details
                  density="compact"
                  @update:model-value="(val: boolean | null) => { if (val) selectedIds = [...selectedIds, v.id]; else selectedIds = selectedIds.filter(id => id !== v.id) }"
                />
              </td>
              <td v-for="optName in optionColumns" :key="optName">
                <template v-if="optionSetType(optName) === 'image'">
                  <v-img
                    v-if="optionImagePathForColumn(optName, (v.option_values || {})[optName])"
                    :src="optionImageUrl(optionImagePathForColumn(optName, (v.option_values || {})[optName]))"
                    width="48"
                    height="32"
                    cover
                    class="rounded border"
                  />
                  <span v-else>–</span>
                </template>
                <template v-else>
                  {{ optionValueForColumn(optName, (v.option_values || {})[optName]) || '–' }}
                </template>
              </td>
              <td>{{ v.name }}</td>
              <td>
                <v-text-field v-model="v.sku" variant="outlined" density="compact" hide-details class="mt-1" style="max-width: 120px" @blur="saveVariant(v)" />
              </td>
              <td>
                <v-text-field v-model.number="v.price" type="number" step="0.01" variant="outlined" density="compact" hide-details class="mt-1" style="max-width: 100px" @blur="saveVariant(v)" />
              </td>
              <td>
                <v-switch
                  v-model="v.track_stock"
                  hide-details
                  density="compact"
                  color="primary"
                  @update:model-value="saveVariant(v)"
                />
              </td>
              <td>
                <v-text-field
                  v-model.number="v.stock"
                  type="number"
                  min="0"
                  variant="outlined"
                  density="compact"
                  hide-details
                  class="mt-1"
                  style="max-width: 80px"
                  :disabled="v.track_stock === false"
                  @blur="saveVariant(v)"
                />
              </td>
              <td v-if="variants.length > 1">
                <v-btn size="small" variant="text" @click="saveVariant(v)">
                  Save
                </v-btn>
              </td>
            </tr>
          </tbody>
        </v-table>
      </v-card-text>
    </v-card>
    <v-dialog v-model="showVariant" max-width="500" persistent>
      <v-card>
        <v-card-title>New variant</v-card-title>
        <v-card-text>
          <v-text-field v-model="variantForm.name" label="Name" variant="outlined" class="mb-2" />
          <v-text-field v-model="variantForm.sku" label="SKU (optional, auto-generate if empty)" variant="outlined" class="mb-2" />
          <v-text-field v-model.number="variantForm.price" label="Price" type="number" step="0.01" variant="outlined" />
          <v-checkbox v-model="variantForm.track_stock" label="Track stock for this variant" />
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" @click="showVariant = false">Cancel</v-btn>
          <v-btn color="primary" :loading="saving" @click="addVariant">Add</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </div>
  <div v-else class="text-center py-8">
    <v-progress-circular indeterminate />
  </div>
  <StorageImagePickerDialog
    v-model="showImagePicker"
    :selected-path="currentPickerSelectedPath"
    @selected="onImageSelected"
  />
  <StorageImagePickerDialog
    v-model="showProductImagePicker"
    @selected="onProductImageSelected"
  />
  <ProductMetadataCreateDialog
    v-model="showBrandDialog"
    type="brand"
    :categories="categories"
    @created="onBrandCreated"
  />
  <ProductMetadataCreateDialog
    v-model="showCategoryDialog"
    type="category"
    :categories="categories"
    @created="onCategoryCreated"
  />
  <ProductMetadataCreateDialog
    v-model="showTagDialog"
    type="tag"
    :categories="categories"
    @created="onTagCreated"
  />
  <v-dialog v-model="showScannerDialog" max-width="640" persistent>
    <v-card>
      <v-card-title>Scan product barcode</v-card-title>
      <v-card-text>
        <p class="text-caption text-medium-emphasis mb-2">
          Allow camera access and point the camera at the barcode.
        </p>
        <div class="scanner-stage">
          <video ref="scannerVideoRef" class="scanner-video" autoplay muted playsinline />
          <div class="scanner-guide">
            <div class="scanner-line" />
          </div>
        </div>
        <p class="text-caption text-medium-emphasis mt-2 mb-0">
          Place barcode inside the frame.
        </p>
        <p v-if="scannerError" class="text-caption text-error mt-2 mb-0">
          {{ scannerError }}
        </p>
        <div class="d-flex align-center ga-2 mt-3">
          <input
            ref="scannerImageInputRef"
            type="file"
            accept="image/*"
            class="d-none"
            @change="onBarcodeImageSelected"
          >
          <v-btn variant="outlined" prepend-icon="mdi-image-search-outline" :loading="scannerImageLoading" @click="scannerImageInputRef?.click()">
            Scan from image
          </v-btn>
          <span class="text-caption text-medium-emphasis">
            You can also upload a barcode photo.
          </span>
        </div>
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn variant="text" @click="closeScanDialog">Close</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup lang="ts">
definePageMeta({ layout: 'admin', middleware: 'role' })

const route = useRoute()
const config = useRuntimeConfig()
const id = route.params.id as string
const product = ref<any>(null)
const variants = ref<any[]>([])
const images = ref<any[]>([])
const brands = ref<any[]>([])
const categories = ref<any[]>([])
const tags = ref<any[]>([])
const showBrandDialog = ref(false)
const showCategoryDialog = ref(false)
const showTagDialog = ref(false)
const optionSetsLocal = ref<Array<{
  name: string
  type: 'text' | 'image' | 'color'
  valuesText: string
  entries: Array<{ label: string; value: string }>
}>>([])
const showVariant = ref(false)
const saving = ref(false)
const generating = ref(false)
const generatingBarcode = ref(false)
const bulkSaving = ref(false)
const bulkPrice = ref<string>('')
const bulkStock = ref<string>('')
const selectedIds = ref<string[]>([])
const showScannerDialog = ref(false)
const scannerError = ref('')
const scannerImageLoading = ref(false)
const scannerVideoRef = ref<HTMLVideoElement | null>(null)
const scannerImageInputRef = ref<HTMLInputElement | null>(null)
let scannerControls: { stop: () => void } | null = null
let scannerReader: any = null
const variantForm = reactive({ name: '', sku: '', price: 0, track_stock: true })
const showImagePicker = ref(false)
const showProductImagePicker = ref(false)
const pickerTarget = ref<{ optionIdx: number; entryIdx: number } | null>(null)
const currentPickerSelectedPath = computed(() => {
  if (!pickerTarget.value) return ''
  const target = optionSetsLocal.value[pickerTarget.value.optionIdx]
  if (!target) return ''
  return target.entries[pickerTarget.value.entryIdx]?.value ?? ''
})
const optionTypeItems = [
  { title: 'Text', value: 'text' },
  { title: 'Image', value: 'image' },
  { title: 'Color', value: 'color' },
]

const optionColumns = computed(() => {
  const sets = product.value?.option_sets as Array<{ name: string }> | undefined
  return sets?.map(s => s.name) ?? []
})

const optionSetsChanged = computed(() => {
  const current = normalizeOptionSetsFromApi(product.value?.option_sets)
  const a = JSON.stringify(current)
  const b = JSON.stringify(buildOptionSetsPayload())
  if (!current.length && !buildOptionSetsPayload().length) return false
  return a !== b
})

function normalizeOptionSetsFromApi(raw: any): Array<{ name: string; type: 'text' | 'image' | 'color'; values: Array<{ label: string; value: string }> }> {
  const list = Array.isArray(raw) ? raw : []
  return list
    .map((o: any) => {
      const type = (o?.type ?? 'text') as 'text' | 'image' | 'color'
      const values = Array.isArray(o?.values) ? o.values : []
      const normalizedValues = values
        .map((v: any) => {
          if (typeof v === 'string') {
            const clean = v.trim()
            if (!clean) return null
            return { label: clean, value: clean }
          }
          const label = String(v?.label ?? '').trim()
          const value = String(v?.value ?? '').trim()
          if (!label || !value) return null
          return { label, value }
        })
        .filter(Boolean) as Array<{ label: string; value: string }>

      if (!o?.name || !normalizedValues.length) return null
      return {
        name: String(o.name).trim(),
        type,
        values: normalizedValues,
      }
    })
    .filter(Boolean) as Array<{ name: string; type: 'text' | 'image' | 'color'; values: Array<{ label: string; value: string }> }>
}

function toOptionSetLocal(set: { name: string; type: 'text' | 'image' | 'color'; values: Array<{ label: string; value: string }> }) {
  return {
    name: set.name,
    type: set.type,
    valuesText: set.type === 'text' ? set.values.map(v => v.label).join(', ') : '',
    entries: set.type === 'text' ? [] : set.values.map(v => ({ label: v.label, value: v.value })),
  }
}

function buildOptionSetsPayload() {
  return optionSetsLocal.value
    .map((o) => {
      const name = o.name.trim()
      if (!name) return null
      if (o.type === 'text') {
        const values = o.valuesText.split(',').map(v => v.trim()).filter(Boolean)
        if (!values.length) return null
        return { name, type: 'text' as const, values: values.map(v => ({ label: v, value: v })) }
      }
      const entries = o.entries
        .map(e => ({ label: e.label.trim(), value: e.value.trim() }))
        .filter(e => e.label && e.value)
      if (!entries.length) return null
      return { name, type: o.type, values: entries }
    })
    .filter(Boolean)
}

function addOptionSet(type: 'text' | 'image' | 'color') {
  optionSetsLocal.value.push({
    name: '',
    type,
    valuesText: '',
    entries: type === 'text' ? [] : [{ label: '', value: type === 'color' ? '#000000' : '' }],
  })
}

function optionValueForColumn(optionName: string, optionValue?: string) {
  if (!optionValue) return ''
  const set = normalizeOptionSetsFromApi(product.value?.option_sets).find(s => s.name === optionName)
  if (!set) return optionValue
  const matched = set.values.find(v => v.label === optionValue || v.value === optionValue)
  return matched?.label ?? optionValue
}

function optionSetType(optionName: string) {
  const set = normalizeOptionSetsFromApi(product.value?.option_sets).find(s => s.name === optionName)
  return set?.type ?? 'text'
}

function optionImagePathForColumn(optionName: string, optionValue?: string) {
  if (!optionValue) return ''
  const set = normalizeOptionSetsFromApi(product.value?.option_sets).find(s => s.name === optionName)
  if (!set || set.type !== 'image') return ''
  const matched = set.values.find(v => v.label === optionValue || v.value === optionValue)
  return matched?.value ?? ''
}

function optionImageUrl(path: string) {
  if (!path) return ''
  if (path.startsWith('http://') || path.startsWith('https://'))
    return path
  const base = config.public.supabaseUrl as string
  return base ? `${base}/storage/v1/object/public/product-images/${path}` : path
}

function openImagePicker(optionIdx: number, entryIdx: number) {
  pickerTarget.value = { optionIdx, entryIdx }
  showImagePicker.value = true
}

function onImageSelected(path: string) {
  if (!pickerTarget.value) return
  const target = optionSetsLocal.value[pickerTarget.value.optionIdx]
  if (!target) return
  const entry = target.entries[pickerTarget.value.entryIdx]
  if (!entry) return
  entry.value = path
  pickerTarget.value = null
  showImagePicker.value = false
}

function imageUrl(path: string) {
  const base = config.public.supabaseUrl as string
  if (!base) return path
  return `${base}/storage/v1/object/public/product-images/${path}`
}

async function load() {
  try {
    const data = await $fetch<any>('/api/admin/products/' + id)
    product.value = data
    product.value.category_ids = data.category_ids ?? []
    product.value.tag_ids = data.tag_ids ?? []
    if (product.value.track_stock == null)
      product.value.track_stock = true
    variants.value = (data.variants ?? []).map((v: any) => ({
      ...v,
      track_stock: v.track_stock !== false,
    }))
    images.value = data.images ?? []
    const sets = normalizeOptionSetsFromApi(data.option_sets)
    optionSetsLocal.value = sets.map(toOptionSetLocal)
  }
  catch {
    product.value = null
    variants.value = []
    images.value = []
  }
}

async function updateProduct() {
  if (!product.value) return
  const body: any = {
    name: product.value.name,
    slug: product.value.slug,
    description: isRichTextEmpty(product.value.description) ? '' : product.value.description,
    barcode: product.value.barcode?.trim() || null,
    brand_id: product.value.brand_id ?? null,
    category_ids: product.value.category_ids ?? [],
    tag_ids: product.value.tag_ids ?? [],
    is_active: product.value.is_active,
    track_stock: product.value.track_stock,
  }
  if (product.value.has_variants && product.value.option_sets)
    body.option_sets = product.value.option_sets
  await $fetch(`/api/admin/products/${id}`, { method: 'PUT', body })
}

async function shuffleBarcode() {
  generatingBarcode.value = true
  try {
    const result = await $fetch<{ barcode: string }>('/api/admin/products/barcode/generate')
    if (product.value)
      product.value.barcode = result.barcode
    await updateProduct()
  }
  finally {
    generatingBarcode.value = false
  }
}

async function openScanDialog() {
  showScannerDialog.value = true
  await nextTick()
  await startScanner()
}

function stopScanner() {
  if (!scannerControls) return
  try {
    scannerControls.stop()
  }
  finally {
    scannerControls = null
  }
}

async function startScanner() {
  if (!import.meta.client) return
  scannerError.value = ''
  stopScanner()
  if (!scannerVideoRef.value) return
  try {
    const { BrowserMultiFormatReader } = await import('@zxing/browser')
    const { BarcodeFormat, DecodeHintType } = await import('@zxing/library')
    if (!scannerReader) {
      const hints = new Map<any, any>()
      hints.set(DecodeHintType.POSSIBLE_FORMATS, [
        BarcodeFormat.CODE_128,
        BarcodeFormat.EAN_13,
        BarcodeFormat.EAN_8,
        BarcodeFormat.UPC_A,
        BarcodeFormat.UPC_E,
        BarcodeFormat.CODE_39,
        BarcodeFormat.ITF,
      ])
      hints.set(DecodeHintType.TRY_HARDER, true)
      scannerReader = new BrowserMultiFormatReader(hints)
    }
    scannerControls = await scannerReader.decodeFromConstraints(
      {
        video: {
          facingMode: { ideal: 'environment' },
          width: { ideal: 1920 },
          height: { ideal: 1080 },
        },
      },
      scannerVideoRef.value,
      (result: any, error: any) => {
        if (result?.getText) {
          if (product.value)
            product.value.barcode = String(result.getText()).trim()
          closeScanDialog()
          updateProduct()
          return
        }
        const errName = String(error?.name ?? '')
        if (error && errName && !['NotFoundException', 'ChecksumException', 'FormatException'].includes(errName))
          scannerError.value = error?.message || 'Camera scanning failed.'
      },
    )
  }
  catch (e: any) {
    scannerError.value = humanizeScannerError(e)
  }
}

function closeScanDialog() {
  showScannerDialog.value = false
  stopScanner()
}

async function onBarcodeImageSelected(e: Event) {
  const input = e.target as HTMLInputElement
  const file = input.files?.[0]
  if (!file) return
  scannerImageLoading.value = true
  scannerError.value = ''
  try {
    const { BrowserMultiFormatReader } = await import('@zxing/browser')
    if (!scannerReader)
      scannerReader = new BrowserMultiFormatReader()
    const url = URL.createObjectURL(file)
    try {
      const result = await scannerReader.decodeFromImageUrl(url)
      const code = result?.getText?.() ? String(result.getText()).trim() : ''
      if (!code)
        throw new Error('No barcode found in selected image.')
      if (product.value)
        product.value.barcode = code
      closeScanDialog()
      await updateProduct()
    }
    finally {
      URL.revokeObjectURL(url)
    }
  }
  catch (e: any) {
    scannerError.value = humanizeScannerError(e)
  }
  finally {
    scannerImageLoading.value = false
    input.value = ''
  }
}

function humanizeScannerError(error: any) {
  const msg = String(error?.message ?? '')
  if (!msg) return 'Scanner failed. Please try again.'
  if (msg.includes('No MultiFormat Readers were able to detect the code'))
    return 'No barcode detected. Try a clearer image with better lighting and full barcode in frame.'
  if (msg.toLowerCase().includes('permission'))
    return 'Camera permission denied. Please allow camera access in browser settings.'
  if (msg.toLowerCase().includes('notfounderror'))
    return 'No camera device found.'
  if (msg.toLowerCase().includes('notreadableerror'))
    return 'Camera is busy in another app/tab. Close it and retry.'
  if (msg.toLowerCase().includes('overconstrainederror'))
    return 'Camera constraints are not supported on this device. Please try scan from image.'
  return msg
}

function saveOptionSets() {
  const sets = buildOptionSetsPayload()
  product.value.option_sets = sets
  updateProduct()
}

async function addVariant() {
  saving.value = true
  try {
    await $fetch(`/api/admin/products/${id}/variants`, {
      method: 'POST',
      body: {
        name: variantForm.name,
        sku: variantForm.sku || undefined,
        price: variantForm.price,
        track_stock: variantForm.track_stock,
      },
    })
    showVariant.value = false
    variantForm.name = ''
    variantForm.sku = ''
    variantForm.price = 0
    variantForm.track_stock = true
    await load()
  }
  finally {
    saving.value = false
  }
}

async function saveVariant(v: any) {
  const updates = [{
    variant_id: v.id,
    price: Number(v.price),
    stock: Number(v.stock),
    track_stock: v.track_stock !== false,
  }]
  await $fetch(`/api/admin/products/${id}/variants/bulk`, { method: 'PATCH', body: { updates } })
}

function toggleSelectAll() {
  if (selectedIds.value.length === variants.value.length) {
    selectedIds.value = []
  } else {
    selectedIds.value = variants.value.map((x: any) => x.id)
  }
}

async function applyBulkEdit() {
  const ids = selectedIds.value
  if (ids.length === 0) return
  const updates = ids.map(variant_id => {
    const u: any = { variant_id }
    const p = Number(bulkPrice.value)
    const s = Number(bulkStock.value)
    if (!Number.isNaN(p) && bulkPrice.value !== '') u.price = p
    if (!Number.isNaN(s) && bulkStock.value !== '') u.stock = s
    return u
  }).filter(u => u.price !== undefined || u.stock !== undefined)
  if (updates.length === 0) return
  bulkSaving.value = true
  try {
    await $fetch(`/api/admin/products/${id}/variants/bulk`, { method: 'PATCH', body: { updates } })
    bulkPrice.value = ''
    bulkStock.value = ''
    selectedIds.value = []
    await load()
  }
  finally {
    bulkSaving.value = false
  }
}

async function generateVariants() {
  generating.value = true
  try {
    const payload = buildOptionSetsPayload()
    await $fetch(`/api/admin/products/${id}/variants/generate`, {
      method: 'POST',
      body: { option_sets: payload },
    })
    await load()
  }
  finally {
    generating.value = false
  }
}

async function onProductImageSelected(path: string) {
  if (!path) return
  await $fetch(`/api/admin/products/${id}/images`, {
    method: 'POST',
    body: { path },
  })
  await load()
}

async function deleteImage(imageId: string) {
  await $fetch(`/api/admin/products/${id}/images/${imageId}`, { method: 'DELETE' })
  await load()
}

async function loadMetadata() {
  const data = await $fetch<any>('/api/admin/product-metadata')
  brands.value = data?.brands ?? []
  categories.value = data?.categories ?? []
  tags.value = data?.tags ?? []
}

function onBrandCreated(item: any) {
  brands.value = [...brands.value, item]
  if (product.value)
    product.value.brand_id = item.id
  updateProduct()
}

function onCategoryCreated(item: any) {
  categories.value = [...categories.value, item]
  if (product.value) {
    const ids = new Set([...(product.value.category_ids ?? []), item.id])
    product.value.category_ids = [...ids]
  }
  updateProduct()
}

function onTagCreated(item: any) {
  tags.value = [...tags.value, item]
  if (product.value) {
    const ids = new Set([...(product.value.tag_ids ?? []), item.id])
    product.value.tag_ids = [...ids]
  }
  updateProduct()
}

onMounted(async () => {
  await loadMetadata()
  await load()
})

onBeforeUnmount(() => {
  stopScanner()
})
</script>

<style scoped>
.image-preview-btn {
  width: 84px;
  height: 48px;
  border: 1px solid rgba(148, 163, 184, 0.4);
  border-radius: 8px;
  overflow: hidden;
  padding: 0;
  cursor: pointer;
}

.product-description-editor {
  margin-bottom: 16px;
}

.product-description-editor :deep(.rich-editor-content .rich-editor-input) {
  min-height: 256px;
}

.scanner-video {
  width: 100%;
  min-height: 260px;
  max-height: 380px;
  border-radius: 10px;
  border: 1px solid rgba(148, 163, 184, 0.35);
  background: #0f172a;
  object-fit: cover;
}

.scanner-stage {
  position: relative;
}

.scanner-guide {
  pointer-events: none;
  position: absolute;
  left: 50%;
  top: 50%;
  width: min(86%, 420px);
  height: min(54%, 180px);
  transform: translate(-50%, -50%);
  border: 2px solid rgba(34, 197, 94, 0.9);
  border-radius: 10px;
  box-shadow: 0 0 0 9999px rgba(2, 6, 23, 0.25);
  overflow: hidden;
}

.scanner-line {
  position: absolute;
  left: 0;
  right: 0;
  height: 2px;
  background: rgba(34, 197, 94, 0.95);
  box-shadow: 0 0 10px rgba(34, 197, 94, 0.75);
  animation: scanner-line-move 1.8s linear infinite;
}

@keyframes scanner-line-move {
  0% { top: 0; }
  100% { top: calc(100% - 2px); }
}
</style>
